### ISSUE TITLE
table async select (tracker)

### ISSUE THREAD

**Issue by a0m0rajab** [ayasofyazilim-clomerce/ayasofyazilim-ui#490]
- [x] remove element after select
- [x] fix types and make it generic for any input type
- [x] make chips/badges style of select in the sheet
- [ ] close the sheet on save 
- [x] fix the show style on the main table

**Comment by a0m0rajab** [comment]
Related PRs:
- https://github.com/ayasofyazilim-clomerce/ayasofyazilim-ui/pull/498
- https://github.com/ayasofyazilim-clomerce/ayasofyazilim-ui/pull/492
- https://github.com/ayasofyazilim-clomerce/ayasofyazilim-ui/pull/489
